merge: ./source/merge.cpp
	g++ ./source/merge.cpp -o ./build/merge

merge0: ./source/merge0.cpp
	g++ ./source/merge0.cpp -o ./build/merge0

quick: ./source/quick.cpp
	g++ ./source/quick.cpp -o ./build/quick

carnie: ./source/carnie.cpp
	g++ ./source/carnie.cpp -o ./build/carnie

trans: ./source/trans.cpp
	g++ ./source/trans.cpp -o ./build/trans

clean:
	rm -f ./build/*
