foo: ./source/foo.cpp
	g++ ./source/foo.cpp -o ./build/foo
bar: ./source/bar.cpp
	g++ ./source/bar.cpp -o ./build/bar
main: ./source/main.cpp
	g++ ./source/main.cpp -o ./build/lists
clean:
	rm -f ./build/*
